{
 "title": "K6 real-time results",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "test_run_id", "query": "null" }
  ]
 },
 "panels": [
  {
   "title": "http_reqs_per_second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => if \"${test_run_id}\" == \"null\" then true else r[\"test_run_id\"] == \"${test_run_id}\")\n  |> group(columns: [\"scenario\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\n  |> yield(name: \"http_reqs_per_second\")\n"
    }
   ]
  },
  {
   "title": "iterations_per_second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iterations\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => if \"${test_run_id}\" == \"null\" then true else r[\"test_run_id\"] == \"${test_run_id}\")\n  |> group(columns: [\"scenario\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\n  |> yield(name: \"iterations_per_second\")\n"
    }
   ]
  },
  {
   "title": "http_req_duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => if \"${test_run_id}\" == \"null\" then true else r[\"test_run_id\"] == \"${test_run_id}\")\n  |> group(columns: [])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"mean\")\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => if \"${test_run_id}\" == \"null\" then true else r[\"test_run_id\"] == \"${test_run_id}\")\n  |> group(columns: [])\n  |> aggregateWindow(every: v.windowPeriod, fn: (tables=<-, column) => tables |> quantile(q: 0.5))\n  |> yield(name: \"p50\")\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => if \"${test_run_id}\" == \"null\" then true else r[\"test_run_id\"] == \"${test_run_id}\")\n  |> group(columns: [])\n  |> aggregateWindow(every: v.windowPeriod, fn: (tables=<-, column) => tables |> quantile(q: 0.95))\n  |> yield(name: \"p95\")\n"
    }
   ]
  },
  {
   "title": "iteration_duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"iteration_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => if \"${test_run_id}\" == \"null\" then true else r[\"test_run_id\"] == \"${test_run_id}\")\n  |> group(columns: [\"scenario\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"mean\")\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"iteration_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => if \"${test_run_id}\" == \"null\" then true else r[\"test_run_id\"] == \"${test_run_id}\")\n  |> group(columns: [\"scenario\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: (tables=<-, column) => tables |> quantile(q: 0.5))\n  |> yield(name: \"p50\")\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"iteration_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => if \"${test_run_id}\" == \"null\" then true else r[\"test_run_id\"] == \"${test_run_id}\")\n  |> group(columns: [\"scenario\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: (tables=<-, column) => tables |> quantile(q: 0.95))\n  |> yield(name: \"p95\")\n"
    }
   ]
  },
  {
   "title": "http_req_failed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => if \"${test_run_id}\" == \"null\" then true else r[\"test_run_id\"] == \"${test_run_id}\")\n  |> group(columns: [\"scenario\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"http_req_failed\")"
    }
   ]
  }
 ]
}